name: langgraph
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - alsa-lib=1.2.12
  - annotated-types=0.6.0
  - anyio=4.2.0
  - aom=3.9.1
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=23.1.0
  - beautifulsoup4=4.12.3
  - binutils_impl_linux-64=2.38
  - binutils_linux-64=2.38.0
  - blas=1.0
  - blosc=1.21.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.12.31
  - cairo=1.18.0
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.7
  - contourpy=1.2.0
  - cuda-cccl_linux-64=12.6.37
  - cuda-crt-dev_linux-64=12.6.68
  - cuda-crt-tools=12.6.68
  - cuda-cudart=12.6.68
  - cuda-cudart-dev=12.6.68
  - cuda-cudart-dev_linux-64=12.6.68
  - cuda-cudart-static=12.6.68
  - cuda-cudart-static_linux-64=12.6.68
  - cuda-cudart_linux-64=12.6.68
  - cuda-cupti=12.6.68
  - cuda-driver-dev_linux-64=12.6.68
  - cuda-nvcc=12.6.68
  - cuda-nvcc-dev_linux-64=12.6.68
  - cuda-nvcc-impl=12.6.68
  - cuda-nvcc-tools=12.6.68
  - cuda-nvcc_linux-64=12.6.68
  - cuda-nvrtc=12.6.68
  - cuda-nvtx=12.6.68
  - cuda-nvvm-dev_linux-64=12.6.68
  - cuda-nvvm-impl=12.6.68
  - cuda-nvvm-tools=12.6.68
  - cuda-version=12.6
  - cudnn=8.9.7.29
  - cycler=0.11.0
  - dataclasses-json=0.6.5
  - dav1d=1.2.1
  - dbus=1.13.18
  - diskcache=5.6.3
  - distro=1.9.0
  - double-conversion=3.3.0
  - eigen=3.4.0
  - expat=2.6.3
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gitdb=4.0.7
  - gitpython=3.1.43
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.14
  - greenlet=3.0.1
  - gst-plugins-base=1.24.4
  - gstreamer=1.24.4
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - h11=0.14.0
  - harfbuzz=8.5.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - httpcore=1.0.2
  - httpx=0.27.0
  - httpx-sse=0.4.0
  - icu=73.2
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - jiter=0.5.0
  - jsoncpp=1.9.5
  - jsonpatch=1.33
  - jsonpointer=2.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - langchain=0.3.18
  - langchain-community=0.3.17
  - langchain-core=0.3.34
  - langchain-experimental=0.3.4
  - langchain-text-splitters=0.3.6
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.69
  - libclang-cpp15=15.0.7
  - libclang-cpp18.1=18.1.7
  - libclang13=18.1.7
  - libcublas=12.6.1.4
  - libcufft=11.2.6.59
  - libcups=2.3.3
  - libcurand=10.3.7.68
  - libcurl=8.8.0
  - libcusolver=11.6.4.69
  - libcusparse=12.5.3.3
  - libdeflate=1.20
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libglu=9.0.0
  - libgomp=14.1.0
  - libgpg-error=1.50
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - libllvm15=15.0.7
  - libllvm18=18.1.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libnvjitlink=12.6.68
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopenvino=2024.1.0
  - libopenvino-auto-batch-plugin=2024.1.0
  - libopenvino-auto-plugin=2024.1.0
  - libopenvino-hetero-plugin=2024.1.0
  - libopenvino-intel-cpu-plugin=2024.1.0
  - libopenvino-intel-gpu-plugin=2024.1.0
  - libopenvino-intel-npu-plugin=2024.1.0
  - libopenvino-ir-frontend=2024.1.0
  - libopenvino-onnx-frontend=2024.1.0
  - libopenvino-paddle-frontend=2024.1.0
  - libopenvino-pytorch-frontend=2024.1.0
  - libopenvino-tensorflow-frontend=2024.1.0
  - libopenvino-tensorflow-lite-frontend=2024.1.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsndfile=1.2.2
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=256.7
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.21.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.1
  - libzip=1.10.1
  - libzlib=1.2.13
  - llama.cpp=0.0.1660
  - loguru=0.5.3
  - lz4-c=1.9.4
  - marshmallow=3.19.0
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mpg123=1.32.6
  - msgpack-python=1.1.0
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nccl=2.23.4.1
  - ncurses=6.4
  - nettle=3.9.1
  - nlohmann_json=3.11.2
  - nspr=4.35
  - nss=3.100
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - opt-einsum=3.4.0
  - opt_einsum=3.4.0
  - p11-kit=0.24.1
  - packaging=24.1
  - pcre2=10.43
  - pixman=0.43.2
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - proj=9.3.1
  - pugixml=1.14
  - pulseaudio-client=17.0
  - pydantic-settings=2.5.2
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python_abi=3.11
  - pyvista=0.44.1
  - pyyaml=6.0.1
  - qt-main=5.15.8
  - qt6-main=6.7.1
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - scooby=0.10.0
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.34
  - sqlite=3.45.3
  - sse-starlette=2.1.3
  - starlette-context=0.3.6
  - svt-av1=2.1.0
  - sysroot_linux-64=2.17
  - tbb=2021.13.0
  - tbb-devel=2021.13.0
  - tenacity=8.2.3
  - termcolor=2.3.0
  - tiktoken=0.7.0
  - tk=8.6.14
  - tornado=6.4.1
  - tqdm=4.66.5
  - trimesh=4.0.0
  - typing-extensions=4.11.0
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - utfcpp=3.2.1
  - vtk=9.3.0
  - vtk-base=9.3.0
  - vtk-io-ffmpeg=9.3.0
  - wayland=1.23.1
  - wheel=0.43.0
  - wslink=2.2.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.42
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==0.26.0
      - aiofiles==23.2.1
      - aiohttp-cors==0.7.0
      - airportsdata==20241001
      - aliyun-python-sdk-core==2.15.2
      - aliyun-python-sdk-kms==2.16.5
      - anthropic==0.36.0
      - antlr4-python3-runtime==4.9.3
      - astor==0.8.1
      - asttokens==3.0.0
      - audioread==3.0.1
      - autoawq==0.2.6+cu121
      - autoawq-kernels==0.0.8
      - bitsandbytes==0.44.1
      - blake3==1.0.4
      - cachetools==5.5.0
      - cffi==1.17.1
      - chardet==5.2.0
      - cloudpickle==3.1.0
      - cmake==3.30.4
      - colorama==0.4.6
      - colorful==0.5.6
      - compressed-tensors==0.9.1
      - crcmod==1.7
      - cryptography==43.0.1
      - cuda-bindings==12.8.0
      - cuda-python==12.8.0
      - dataproperty==1.1.0
      - datasets==3.0.1
      - decorator==5.1.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - depyf==0.18.0
      - dill==0.3.8
      - distlib==0.3.9
      - e==1.4.5
      - editdistance==0.8.1
      - einops==0.8.0
      - etils==1.10.0
      - executing==2.2.0
      - fastapi==0.115.0
      - ffmpy==0.4.0
      - filelock==3.16.1
      - filetype==1.2.0
      - flashinfer==0.1.6+cu124torch2.4
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - funasr==1.1.6
      - gguf==0.10.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.24.0
      - google-api-python-client==2.155.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.66.0
      - gradio==4.44.0
      - gradio-client==1.3.0
      - groq==0.17.0
      - grpcio==1.68.1
      - grpcio-status==1.68.1
      - hf-transfer==0.1.9
      - httplib2==0.22.0
      - httptools==0.6.4
      - huggingface-hub==0.25.0
      - humanize==4.11.0
      - hydra-core==1.3.2
      - imageio==2.37.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - interegular==0.3.3
      - ipython==8.32.0
      - jaconv==0.4.0
      - jamo==0.4.1
      - jax==0.4.34
      - jax-cuda12-pjrt==0.4.34
      - jax-cuda12-plugin==0.4.34
      - jaxlib==0.4.34
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.4
      - jmespath==0.10.0
      - jmp==0.0.4
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kaldiio==2.18.0
      - langchain-anthropic==0.2.3
      - langchain-google-genai==2.0.7
      - langchain-groq==0.2.4
      - langchain-ollama==0.2.3
      - langchain-openai==0.3.4
      - langchain-xai==0.2.0
      - langgraph==0.2.70
      - langgraph-checkpoint==2.0.10
      - langgraph-sdk==0.1.51
      - langsmith==0.1.135
      - lark==1.2.2
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - linkify-it-py==2.0.3
      - litellm==1.60.0
      - llama-cpp-python==0.2.90
      - llvmlite==0.43.0
      - lm-eval==0.3.0
      - lm-format-enforcer==0.10.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mbstrdecoder==1.1.4
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - memray==1.15.0
      - mistral-common==1.5.2
      - ml-dtypes==0.5.0
      - modelscope==1.22.3
      - mpmath==1.3.0
      - msgspec==0.18.6
      - multiprocess==0.70.16
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.1
      - nltk==3.9.1
      - numba==0.60.0
      - numexpr==2.10.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvcc-cu12==12.6.77
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - ollama==0.4.7
      - omegaconf==2.3.0
      - openai==1.61.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.10.0.84
      - orbax-checkpoint==0.4.4
      - orjson==3.10.15
      - oss2==2.19.0
      - outlines==0.1.11
      - outlines-core==0.1.26
      - pandas==2.2.2
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post4
      - pathvalidate==3.2.3
      - pexpect==4.9.0
      - pillow==10.4.0
      - pip==25.0
      - pluggy==1.5.0
      - portalocker==3.1.1
      - prometheus-client==0.21.0
      - prometheus-fastapi-instrumentator==7.0.0
      - prompt-toolkit==3.0.50
      - proto-plus==1.25.0
      - protobuf==5.28.2
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyairports==2.1.1
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pytablewriter==1.2.1
      - pytest==8.3.4
      - python-multipart==0.0.9
      - pytorch-wpe==0.0.1
      - pytz==2024.2
      - pyzmq==26.2.0
      - ray==2.37.0
      - referencing==0.35.1
      - requests-toolbelt==1.0.0
      - rich==13.8.1
      - rouge-score==0.1.2
      - rpds-py==0.20.0
      - rsa==4.9
      - ruff==0.6.5
      - sacrebleu==1.5.0
      - safetensors==0.4.5
      - scikit-image==0.25.1
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seedir==0.5.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - setproctitle==1.3.4
      - sgl-kernel==0.0.3.post1
      - sglang==0.4.2.post1
      - shellingham==1.5.4
      - smart-open==7.1.0
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - sqlitedict==2.1.0
      - stack-data==0.6.3
      - starlette==0.38.5
      - sympy==1.13.1
      - tabledata==1.3.4
      - tcolorpy==0.1.7
      - tensorboardx==2.6.2.2
      - tensorstore==0.1.66
      - textual==1.0.0
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - tokenizers==0.21.0
      - tomlkit==0.12.0
      - torch==2.5.1
      - torch-complex==0.4.4
      - torchao==0.8.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm-multiprocess==0.0.11
      - traitlets==5.14.3
      - transformers==4.48.3
      - triton==3.1.0
      - typepy==1.3.4
      - typer==0.12.5
      - tzdata==2024.1
      - uc-micro-py==1.0.3
      - umap-learn==0.5.6
      - uritemplate==4.1.1
      - uvicorn==0.30.6
      - uvloop==0.21.0
      - virtualenv==20.29.2
      - vllm==0.7.2
      - watchfiles==0.24.0
      - wcwidth==0.2.13
      - websockets==12.0
      - wrapt==1.17.2
      - xformers==0.0.28.post3
      - xgrammar==0.1.11
      - xxhash==3.5.0
      - zstandard==0.23.0
